# adapted from https://github.com/spacetelescope/notebook-ci-actions

name: ci_validation 

on:
    push:
      branches: [ "bw-nb-ci" ]

permissions: write-all

jobs:
  example-3:
    name: Ex3 Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: exocore
          environment-file: environment.yml
          python-version: 3.13.1
          auto-activate-base: false
      - run: |
          conda info
          conda list
